# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/config.bt_defaults.ipynb (unless otherwise specified).

__all__ = ['path_results', 'path_data', 'file_format', 'verbose', 'save_splits']

# Cell

# ***************************************
# I / O paths, file formats, etc.
# ***************************************
path_results = None
path_data = 'data'
file_format = 'parquet'
verbose = 1

save_splits = dict(training=True,
                  test=True,
                  validation=True,
                  whole=True)