# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/utils/cli.ipynb (unless otherwise specified).

__all__ = ['dsblocks_install_git_hooks']

# Cell
from nbdev.imports import *
from nbdev.export import *
from nbdev.sync import *
from nbdev.merge import *
from nbdev.export2html import *
from nbdev.clean import *
from nbdev.test import *
from fastcore.script import *

# Cell
@call_parse
def dsblocks_install_git_hooks():
    "Install git hooks to clean/trust notebooks automatically"
    try: path = get_config().config_file.parent
    except: path = Path.cwd()
    hook_path = path/'.git'/'hooks'
    fn = hook_path/'pre-commit'
    hook_path.mkdir(parents=True, exist_ok=True)
    fn.write_text("""#!/bin/sh

echo "\n==================== pre-commit hook ===================="
# Export conda environment to yaml file
conda env export > envs/$CONDA_DEFAULT_ENV.yml
git add envs/$CONDA_DEFAULT_ENV.yml
""")

    os.chmod (fn, stat.S_IRUSR | stat.S_IWUSR | stat.S_IXUSR | stat.S_IRGRP | stat.S_IWGRP | stat.S_IXGRP | stat.S_IROTH |  stat.S_IXOTH)

    os.makedirs ('envs', exist_ok=True)