# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/utils/session.ipynb (unless otherwise specified).

__all__ = ['load']

# Cell
import joblib

# block-types
import dsblocks.config.bt_defaults as dflt

# Cell
def load (path=None):
    if path is None: path = f'{dflt.path_session_folder}/last_run/{dflt.session_filename}'
    return joblib.load (path)