# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"path_results": "config.defaults.ipynb",
         "path_data": "config.defaults.ipynb",
         "file_format": "config.defaults.ipynb",
         "overwrite": "config.defaults.ipynb",
         "verbose": "config.defaults.ipynb",
         "Component": "core.block_types.ipynb",
         "SamplingComponent": "core.block_types.ipynb",
         "SklearnComponent": "core.block_types.ipynb",
         "PickleSaverComponent": "core.block_types.ipynb",
         "NoSaverComponent": "core.block_types.ipynb",
         "OneClassSklearnComponent": "core.block_types.ipynb",
         "PandasComponent": "core.block_types.ipynb",
         "Pipeline": "core.block_types.ipynb",
         "PandasPipeline": "core.block_types.ipynb",
         "pipeline_factory": "core.block_types.ipynb",
         "DataConverter": "core.data_conversion.ipynb",
         "NoConverter": "core.data_conversion.ipynb",
         "PandasConverter": "core.data_conversion.ipynb",
         "Window2Dto3Dconverter": "core.data_conversion.ipynb",
         "save_csv": "core.utils.ipynb",
         "save_parquet": "core.utils.ipynb",
         "save_multi_index_parquet": "core.utils.ipynb",
         "save_keras_model": "core.utils.ipynb",
         "save_csv_gz": "core.utils.ipynb",
         "read_csv": "core.utils.ipynb",
         "read_csv_gz": "core.utils.ipynb",
         "DataIO": "core.utils.ipynb",
         "PickleIO": "core.utils.ipynb",
         "SklearnIO": "core.utils.ipynb",
         "NoSaverIO": "core.utils.ipynb",
         "ModelPlotter": "core.utils.ipynb",
         "camel_to_snake": "core.utils.ipynb",
         "DataSet": "datasets.datasets.ipynb",
         "make_reproducible": "utils.utils.ipynb",
         "set_logger": "utils.utils.ipynb",
         "remove_previous_results": "utils.utils.ipynb",
         "set_tf_loglevel": "utils.utils.ipynb"}

modules = ["config/defaults.py",
           "core/block_types.py",
           "core/data_conversion.py",
           "core/utils.py",
           "datasets/datasets.py",
           "utils/utils.py"]

doc_url = "https://Jaume-JCI.github.io/"

git_url = "https://github.com/Jaume-JCI/block_types/blob/main/"

def custom_doc_links(name): return None
