# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_tests/utils/tst.cli.ipynb (unless otherwise specified).

__all__ = ['test_dsblocks_install_git_hooks']

# Cell
import pytest
import os
import joblib
from IPython.display import display

from dsblocks.utils.cli import *
from dsblocks.utils.utils import remove_previous_results

# Comes from cli.ipynb, cell
def test_dsblocks_install_git_hooks ():
    if os.path.exists('.git/hooks/pre-push'):
        os.remove ('.git/hooks/pre-push')

    dsblocks_install_git_hooks ()

    assert {'pre-commit'}.issubset(os.listdir ('.git/hooks'))
    with open('.git/hooks/pre-commit', 'rt') as f: txt = f.read ()
    assert txt.startswith ('#!/bin/sh\n\necho')
    assert txt.endswith ('$CONDA_DEFAULT_ENV.yml\n')

    os.remove ('.git/hooks/pre-commit')