# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_tests/utils/tst.session.ipynb (unless otherwise specified).

__all__ = ['test_load']

# Cell
import pytest
import os
import joblib
from IPython.display import display
import pandas as pd
import numpy as np
import logging
import shutil
from pathlib import Path

from sklearn.utils import Bunch

from dsblocks.utils.session import *
import dsblocks.config.bt_defaults as dflt

# Cell
#@pytest.fixture (name='example_people_data')
#def example_people_data_fixture():
#    return example_people_data()

# Comes from session.ipynb, cell
from dsblocks.utils.dummies import make_pipe1
def test_load ():
    pipe = make_pipe1 ()
    pipe.save_object ()
    pipe2 = load ()
    assert [x.name for x in pipe2.components]==['A', 'B', 'C', 'D', 'E']